FROM python:3.11-slim

WORKDIR /app

COPY house-service /app

RUN pip install --upgrade pip && \
    pip install fastapi uvicorn sqlmodel

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
