# Utiliza a imagem base oficial do Python
FROM python:3.11-slim

# Define o diretório de trabalho no container
WORKDIR /app

# Copia apenas os arquivos necessários para o ambiente no container
COPY . /app

# Cria e ativa o ambiente virtual
RUN python -m venv /venv

# Atualiza o pip e instala as dependências do projeto
RUN /venv/bin/pip install --upgrade pip \
    && /venv/bin/pip install fastapi uvicorn sqlmodel

# Expõe a porta onde o Uvicorn irá rodar
EXPOSE 8000

# Define o comando padrão para iniciar o servidor
CMD ["/venv/bin/uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]